// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: simulation_worker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SimulationWorkerService_SendHeartbeat_FullMethodName    = "/simulation.SimulationWorkerService/SendHeartbeat"
	SimulationWorkerService_StreamJobChannel_FullMethodName = "/simulation.SimulationWorkerService/StreamJobChannel"
)

// SimulationWorkerServiceClient is the client API for SimulationWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationWorkerServiceClient interface {
	// Worker'ın sürekli ayakta olduğunu ve donanım durumunu bildirdiği çağrı
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Çift yönlü akış (Bi-directional Stream): İş dağıtımı, anlık durum ve backend'den gelecek ABORT sinyalleri için
	StreamJobChannel(ctx context.Context, opts ...grpc.CallOption) (SimulationWorkerService_StreamJobChannelClient, error)
}

type simulationWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationWorkerServiceClient(cc grpc.ClientConnInterface) SimulationWorkerServiceClient {
	return &simulationWorkerServiceClient{cc}
}

func (c *simulationWorkerServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, SimulationWorkerService_SendHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationWorkerServiceClient) StreamJobChannel(ctx context.Context, opts ...grpc.CallOption) (SimulationWorkerService_StreamJobChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &SimulationWorkerService_ServiceDesc.Streams[0], SimulationWorkerService_StreamJobChannel_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &simulationWorkerServiceStreamJobChannelClient{stream}
	return x, nil
}

type SimulationWorkerService_StreamJobChannelClient interface {
	Send(*WorkerSignal) error
	Recv() (*BackendSignal, error)
	grpc.ClientStream
}

type simulationWorkerServiceStreamJobChannelClient struct {
	grpc.ClientStream
}

func (x *simulationWorkerServiceStreamJobChannelClient) Send(m *WorkerSignal) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simulationWorkerServiceStreamJobChannelClient) Recv() (*BackendSignal, error) {
	m := new(BackendSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimulationWorkerServiceServer is the server API for SimulationWorkerService service.
// All implementations must embed UnimplementedSimulationWorkerServiceServer
// for forward compatibility
type SimulationWorkerServiceServer interface {
	// Worker'ın sürekli ayakta olduğunu ve donanım durumunu bildirdiği çağrı
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Çift yönlü akış (Bi-directional Stream): İş dağıtımı, anlık durum ve backend'den gelecek ABORT sinyalleri için
	StreamJobChannel(SimulationWorkerService_StreamJobChannelServer) error
	mustEmbedUnimplementedSimulationWorkerServiceServer()
}

// UnimplementedSimulationWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSimulationWorkerServiceServer struct {
}

func (UnimplementedSimulationWorkerServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedSimulationWorkerServiceServer) StreamJobChannel(SimulationWorkerService_StreamJobChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamJobChannel not implemented")
}
func (UnimplementedSimulationWorkerServiceServer) mustEmbedUnimplementedSimulationWorkerServiceServer() {
}

// UnsafeSimulationWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationWorkerServiceServer will
// result in compilation errors.
type UnsafeSimulationWorkerServiceServer interface {
	mustEmbedUnimplementedSimulationWorkerServiceServer()
}

func RegisterSimulationWorkerServiceServer(s grpc.ServiceRegistrar, srv SimulationWorkerServiceServer) {
	s.RegisterService(&SimulationWorkerService_ServiceDesc, srv)
}

func _SimulationWorkerService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationWorkerServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationWorkerService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationWorkerServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationWorkerService_StreamJobChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimulationWorkerServiceServer).StreamJobChannel(&simulationWorkerServiceStreamJobChannelServer{stream})
}

type SimulationWorkerService_StreamJobChannelServer interface {
	Send(*BackendSignal) error
	Recv() (*WorkerSignal, error)
	grpc.ServerStream
}

type simulationWorkerServiceStreamJobChannelServer struct {
	grpc.ServerStream
}

func (x *simulationWorkerServiceStreamJobChannelServer) Send(m *BackendSignal) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simulationWorkerServiceStreamJobChannelServer) Recv() (*WorkerSignal, error) {
	m := new(WorkerSignal)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimulationWorkerService_ServiceDesc is the grpc.ServiceDesc for SimulationWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simulation.SimulationWorkerService",
	HandlerType: (*SimulationWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _SimulationWorkerService_SendHeartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobChannel",
			Handler:       _SimulationWorkerService_StreamJobChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "simulation_worker.proto",
}

const (
	ValidatorService_ValidateJob_FullMethodName = "/simulation.ValidatorService/ValidateJob"
)

// ValidatorServiceClient is the client API for ValidatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidatorServiceClient interface {
	ValidateJob(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
}

type validatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorServiceClient(cc grpc.ClientConnInterface) ValidatorServiceClient {
	return &validatorServiceClient{cc}
}

func (c *validatorServiceClient) ValidateJob(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, ValidatorService_ValidateJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorServiceServer is the server API for ValidatorService service.
// All implementations must embed UnimplementedValidatorServiceServer
// for forward compatibility
type ValidatorServiceServer interface {
	ValidateJob(context.Context, *ValidationRequest) (*ValidationResponse, error)
	mustEmbedUnimplementedValidatorServiceServer()
}

// UnimplementedValidatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedValidatorServiceServer struct {
}

func (UnimplementedValidatorServiceServer) ValidateJob(context.Context, *ValidationRequest) (*ValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateJob not implemented")
}
func (UnimplementedValidatorServiceServer) mustEmbedUnimplementedValidatorServiceServer() {}

// UnsafeValidatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidatorServiceServer will
// result in compilation errors.
type UnsafeValidatorServiceServer interface {
	mustEmbedUnimplementedValidatorServiceServer()
}

func RegisterValidatorServiceServer(s grpc.ServiceRegistrar, srv ValidatorServiceServer) {
	s.RegisterService(&ValidatorService_ServiceDesc, srv)
}

func _ValidatorService_ValidateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorServiceServer).ValidateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidatorService_ValidateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorServiceServer).ValidateJob(ctx, req.(*ValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidatorService_ServiceDesc is the grpc.ServiceDesc for ValidatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simulation.ValidatorService",
	HandlerType: (*ValidatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateJob",
			Handler:    _ValidatorService_ValidateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulation_worker.proto",
}
