// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: simulation_worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Hata Yönetimi ---
type WorkerErrorCode int32

const (
	WorkerErrorCode_SUCCESS             WorkerErrorCode = 0
	WorkerErrorCode_ERR_UNKNOWN         WorkerErrorCode = 1
	WorkerErrorCode_ERR_THERMAL_LIMIT   WorkerErrorCode = 2 // Cihaz aşırı ısındı
	WorkerErrorCode_ERR_HARDWARE_FAULT  WorkerErrorCode = 3 // CUDA/Driver hatası, GPU çöktü
	WorkerErrorCode_ERR_USER_INTERRUPT  WorkerErrorCode = 4 // Bilgisayar sahibi simülasyonu manuel kapattı
	WorkerErrorCode_ERR_OUT_OF_VRAM     WorkerErrorCode = 5 // Molekül/Protein boyutu VRAM'i aştı
	WorkerErrorCode_ERR_DOWNLOAD_FAILED WorkerErrorCode = 6 // PDB veya SMILES girdi dosyaları indirilemedi
)

// Enum value maps for WorkerErrorCode.
var (
	WorkerErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "ERR_UNKNOWN",
		2: "ERR_THERMAL_LIMIT",
		3: "ERR_HARDWARE_FAULT",
		4: "ERR_USER_INTERRUPT",
		5: "ERR_OUT_OF_VRAM",
		6: "ERR_DOWNLOAD_FAILED",
	}
	WorkerErrorCode_value = map[string]int32{
		"SUCCESS":             0,
		"ERR_UNKNOWN":         1,
		"ERR_THERMAL_LIMIT":   2,
		"ERR_HARDWARE_FAULT":  3,
		"ERR_USER_INTERRUPT":  4,
		"ERR_OUT_OF_VRAM":     5,
		"ERR_DOWNLOAD_FAILED": 6,
	}
)

func (x WorkerErrorCode) Enum() *WorkerErrorCode {
	p := new(WorkerErrorCode)
	*p = x
	return p
}

func (x WorkerErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_simulation_worker_proto_enumTypes[0].Descriptor()
}

func (WorkerErrorCode) Type() protoreflect.EnumType {
	return &file_simulation_worker_proto_enumTypes[0]
}

func (x WorkerErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerErrorCode.Descriptor instead.
func (WorkerErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{0}
}

type ValidationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId         string  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ResultAPdbqt  []byte  `protobuf:"bytes,2,opt,name=result_a_pdbqt,json=resultAPdbqt,proto3" json:"result_a_pdbqt,omitempty"`
	ResultAEnergy float64 `protobuf:"fixed64,3,opt,name=result_a_energy,json=resultAEnergy,proto3" json:"result_a_energy,omitempty"`
	ResultBPdbqt  []byte  `protobuf:"bytes,4,opt,name=result_b_pdbqt,json=resultBPdbqt,proto3" json:"result_b_pdbqt,omitempty"`
	ResultBEnergy float64 `protobuf:"fixed64,5,opt,name=result_b_energy,json=resultBEnergy,proto3" json:"result_b_energy,omitempty"`
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ValidationRequest) GetResultAPdbqt() []byte {
	if x != nil {
		return x.ResultAPdbqt
	}
	return nil
}

func (x *ValidationRequest) GetResultAEnergy() float64 {
	if x != nil {
		return x.ResultAEnergy
	}
	return 0
}

func (x *ValidationRequest) GetResultBPdbqt() []byte {
	if x != nil {
		return x.ResultBPdbqt
	}
	return nil
}

func (x *ValidationRequest) GetResultBEnergy() float64 {
	if x != nil {
		return x.ResultBEnergy
	}
	return 0
}

type ValidationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Canlılık Takibi (Heartbeat) ---
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId       string  `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ApiKey         string  `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	GpuTemperature float32 `protobuf:"fixed32,3,opt,name=gpu_temperature,json=gpuTemperature,proto3" json:"gpu_temperature,omitempty"` // Santigrat derece
	FanSpeed       float32 `protobuf:"fixed32,4,opt,name=fan_speed,json=fanSpeed,proto3" json:"fan_speed,omitempty"`                   // Yüzde (%)
	AvailableVram  uint64  `protobuf:"varint,5,opt,name=available_vram,json=availableVram,proto3" json:"available_vram,omitempty"`     // Byte cinsinden
	CurrentFlops   float64 `protobuf:"fixed64,6,opt,name=current_flops,json=currentFlops,proto3" json:"current_flops,omitempty"`       // Anlık hesaplama gücü
	IsBusy         bool    `protobuf:"varint,7,opt,name=is_busy,json=isBusy,proto3" json:"is_busy,omitempty"`                          // Worker o an iş işliyor mu?
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *HeartbeatRequest) GetGpuTemperature() float32 {
	if x != nil {
		return x.GpuTemperature
	}
	return 0
}

func (x *HeartbeatRequest) GetFanSpeed() float32 {
	if x != nil {
		return x.FanSpeed
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableVram() uint64 {
	if x != nil {
		return x.AvailableVram
	}
	return 0
}

func (x *HeartbeatRequest) GetCurrentFlops() float64 {
	if x != nil {
		return x.CurrentFlops
	}
	return 0
}

func (x *HeartbeatRequest) GetIsBusy() bool {
	if x != nil {
		return x.IsBusy
	}
	return false
}

type RewardNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId               string  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NetAmount           float64 `protobuf:"fixed64,2,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	NewConfirmedBalance float64 `protobuf:"fixed64,3,opt,name=new_confirmed_balance,json=newConfirmedBalance,proto3" json:"new_confirmed_balance,omitempty"`
	Status              string  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "CONFIRMED" veya "PENDING_SPOT_CHECK"
}

func (x *RewardNotification) Reset() {
	*x = RewardNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardNotification) ProtoMessage() {}

func (x *RewardNotification) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardNotification.ProtoReflect.Descriptor instead.
func (*RewardNotification) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{3}
}

func (x *RewardNotification) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RewardNotification) GetNetAmount() float64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

func (x *RewardNotification) GetNewConfirmedBalance() float64 {
	if x != nil {
		return x.NewConfirmedBalance
	}
	return 0
}

func (x *RewardNotification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        bool                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Command       string                `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // "COOL_DOWN" veya "PROCEED"
	RecentRewards []*RewardNotification `protobuf:"bytes,3,rep,name=recent_rewards,json=recentRewards,proto3" json:"recent_rewards,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *HeartbeatResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HeartbeatResponse) GetRecentRewards() []*RewardNotification {
	if x != nil {
		return x.RecentRewards
	}
	return nil
}

// --- İş Dağıtımı ve Sinyalleşme ---
type WorkerSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*WorkerSignal_Progress
	//	*WorkerSignal_Result
	Payload isWorkerSignal_Payload `protobuf_oneof:"payload"`
}

func (x *WorkerSignal) Reset() {
	*x = WorkerSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSignal) ProtoMessage() {}

func (x *WorkerSignal) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSignal.ProtoReflect.Descriptor instead.
func (*WorkerSignal) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerSignal) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (m *WorkerSignal) GetPayload() isWorkerSignal_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *WorkerSignal) GetProgress() *WorkerProgress {
	if x, ok := x.GetPayload().(*WorkerSignal_Progress); ok {
		return x.Progress
	}
	return nil
}

func (x *WorkerSignal) GetResult() *JobResult {
	if x, ok := x.GetPayload().(*WorkerSignal_Result); ok {
		return x.Result
	}
	return nil
}

type isWorkerSignal_Payload interface {
	isWorkerSignal_Payload()
}

type WorkerSignal_Progress struct {
	Progress *WorkerProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type WorkerSignal_Result struct {
	Result *JobResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*WorkerSignal_Progress) isWorkerSignal_Payload() {}

func (*WorkerSignal_Result) isWorkerSignal_Payload() {}

type WorkerProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId                string  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CompletionPercentage float32 `protobuf:"fixed32,2,opt,name=completion_percentage,json=completionPercentage,proto3" json:"completion_percentage,omitempty"`
	CurrentEnergyScore   float32 `protobuf:"fixed32,3,opt,name=current_energy_score,json=currentEnergyScore,proto3" json:"current_energy_score,omitempty"`
}

func (x *WorkerProgress) Reset() {
	*x = WorkerProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerProgress) ProtoMessage() {}

func (x *WorkerProgress) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerProgress.ProtoReflect.Descriptor instead.
func (*WorkerProgress) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WorkerProgress) GetCompletionPercentage() float32 {
	if x != nil {
		return x.CompletionPercentage
	}
	return 0
}

func (x *WorkerProgress) GetCurrentEnergyScore() float32 {
	if x != nil {
		return x.CurrentEnergyScore
	}
	return 0
}

type JobResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId           string          `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ErrorCode       WorkerErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=simulation.WorkerErrorCode" json:"error_code,omitempty"`
	ErrorMessage    string          `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutputPdbqtData []byte          `protobuf:"bytes,4,opt,name=output_pdbqt_data,json=outputPdbqtData,proto3" json:"output_pdbqt_data,omitempty"` // Hesaplanan 3D koordinat çıktısı
	BindingEnergy   float64         `protobuf:"fixed64,5,opt,name=binding_energy,json=bindingEnergy,proto3" json:"binding_energy,omitempty"`       // En düşük serbest bağlanma enerjisi (kcal/mol)
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{7}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetErrorCode() WorkerErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return WorkerErrorCode_SUCCESS
}

func (x *JobResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobResult) GetOutputPdbqtData() []byte {
	if x != nil {
		return x.OutputPdbqtData
	}
	return nil
}

func (x *JobResult) GetBindingEnergy() float64 {
	if x != nil {
		return x.BindingEnergy
	}
	return 0
}

type BackendSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*BackendSignal_JobAssignment
	//	*BackendSignal_AbortSignal
	Command isBackendSignal_Command `protobuf_oneof:"command"`
}

func (x *BackendSignal) Reset() {
	*x = BackendSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSignal) ProtoMessage() {}

func (x *BackendSignal) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSignal.ProtoReflect.Descriptor instead.
func (*BackendSignal) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{8}
}

func (m *BackendSignal) GetCommand() isBackendSignal_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *BackendSignal) GetJobAssignment() *JobAssignment {
	if x, ok := x.GetCommand().(*BackendSignal_JobAssignment); ok {
		return x.JobAssignment
	}
	return nil
}

func (x *BackendSignal) GetAbortSignal() *AbortSignal {
	if x, ok := x.GetCommand().(*BackendSignal_AbortSignal); ok {
		return x.AbortSignal
	}
	return nil
}

type isBackendSignal_Command interface {
	isBackendSignal_Command()
}

type BackendSignal_JobAssignment struct {
	JobAssignment *JobAssignment `protobuf:"bytes,1,opt,name=job_assignment,json=jobAssignment,proto3,oneof"`
}

type BackendSignal_AbortSignal struct {
	AbortSignal *AbortSignal `protobuf:"bytes,2,opt,name=abort_signal,json=abortSignal,proto3,oneof"`
}

func (*BackendSignal_JobAssignment) isBackendSignal_Command() {}

func (*BackendSignal_AbortSignal) isBackendSignal_Command() {}

type JobAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId             string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SmilesString      string `protobuf:"bytes,2,opt,name=smiles_string,json=smilesString,proto3" json:"smiles_string,omitempty"`
	TargetPdbUrl      string `protobuf:"bytes,3,opt,name=target_pdb_url,json=targetPdbUrl,proto3" json:"target_pdb_url,omitempty"`
	MaxExhaustiveness int32  `protobuf:"varint,4,opt,name=max_exhaustiveness,json=maxExhaustiveness,proto3" json:"max_exhaustiveness,omitempty"` // Autodock Vina hassasiyet parametresi
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{9}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetSmilesString() string {
	if x != nil {
		return x.SmilesString
	}
	return ""
}

func (x *JobAssignment) GetTargetPdbUrl() string {
	if x != nil {
		return x.TargetPdbUrl
	}
	return ""
}

func (x *JobAssignment) GetMaxExhaustiveness() int32 {
	if x != nil {
		return x.MaxExhaustiveness
	}
	return 0
}

type AbortSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId  string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "USER_CANCELLED" veya "SPOT_CHECK_FAILED"
}

func (x *AbortSignal) Reset() {
	*x = AbortSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulation_worker_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSignal) ProtoMessage() {}

func (x *AbortSignal) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_worker_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSignal.ProtoReflect.Descriptor instead.
func (*AbortSignal) Descriptor() ([]byte, []int) {
	return file_simulation_worker_proto_rawDescGZIP(), []int{10}
}

func (x *AbortSignal) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AbortSignal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_simulation_worker_proto protoreflect.FileDescriptor

var file_simulation_worker_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x69, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x11, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a,
	0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x5f, 0x70,
	0x64, 0x62, 0x71, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x41, 0x50, 0x64, 0x62, 0x71, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x5f, 0x61, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x62, 0x5f, 0x70, 0x64, 0x62,
	0x71, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x42, 0x50, 0x64, 0x62, 0x71, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x5f, 0x62, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x22, 0x49,
	0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf3, 0x01, 0x0a, 0x10, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61,
	0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x67, 0x70, 0x75, 0x5f, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x67,
	0x70, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x61, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x66, 0x61, 0x6e, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x72, 0x61,
	0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x6f,
	0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x46, 0x6c, 0x6f, 0x70, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x62, 0x75, 0x73,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x42, 0x75, 0x73, 0x79, 0x22,
	0x96, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x6e, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x15,
	0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x6e, 0x65, 0x77,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x11, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x45, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x0e,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xd6, 0x01, 0x0a,
	0x09, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x70, 0x64, 0x62,
	0x71, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x64, 0x62, 0x71, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25,
	0x0a, 0x0e, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x45,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x42, 0x0a, 0x0e, 0x6a, 0x6f, 0x62, 0x5f, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x6a, 0x6f,
	0x62, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0c, 0x61,
	0x62, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x62,
	0x6f, 0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x0d, 0x4a, 0x6f, 0x62, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x64, 0x62,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x50, 0x64, 0x62, 0x55, 0x72, 0x6c, 0x12, 0x2d, 0x0a, 0x12, 0x6d, 0x61, 0x78, 0x5f,
	0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x78, 0x45, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74,
	0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x3c, 0x0a, 0x0b, 0x41, 0x62, 0x6f, 0x72, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2a, 0xa4, 0x01, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x52, 0x52, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x52, 0x52, 0x5f, 0x54,
	0x48, 0x45, 0x52, 0x4d, 0x41, 0x4c, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x02, 0x12, 0x16,
	0x0a, 0x12, 0x45, 0x52, 0x52, 0x5f, 0x48, 0x41, 0x52, 0x44, 0x57, 0x41, 0x52, 0x45, 0x5f, 0x46,
	0x41, 0x55, 0x4c, 0x54, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x5f, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x52, 0x55, 0x50, 0x54, 0x10, 0x04, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x52, 0x52, 0x5f, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x56, 0x52, 0x41,
	0x4d, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x52, 0x52, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x06, 0x32, 0xb4, 0x01, 0x0a,
	0x17, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4a, 0x6f, 0x62, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x73, 0x69, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x1a, 0x19, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x28,
	0x01, 0x30, 0x01, 0x32, 0x60, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x1d, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x64, 0x65, 0x70, 0x69, 0x6e, 0x2d, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simulation_worker_proto_rawDescOnce sync.Once
	file_simulation_worker_proto_rawDescData = file_simulation_worker_proto_rawDesc
)

func file_simulation_worker_proto_rawDescGZIP() []byte {
	file_simulation_worker_proto_rawDescOnce.Do(func() {
		file_simulation_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_simulation_worker_proto_rawDescData)
	})
	return file_simulation_worker_proto_rawDescData
}

var file_simulation_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_simulation_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_simulation_worker_proto_goTypes = []interface{}{
	(WorkerErrorCode)(0),       // 0: simulation.WorkerErrorCode
	(*ValidationRequest)(nil),  // 1: simulation.ValidationRequest
	(*ValidationResponse)(nil), // 2: simulation.ValidationResponse
	(*HeartbeatRequest)(nil),   // 3: simulation.HeartbeatRequest
	(*RewardNotification)(nil), // 4: simulation.RewardNotification
	(*HeartbeatResponse)(nil),  // 5: simulation.HeartbeatResponse
	(*WorkerSignal)(nil),       // 6: simulation.WorkerSignal
	(*WorkerProgress)(nil),     // 7: simulation.WorkerProgress
	(*JobResult)(nil),          // 8: simulation.JobResult
	(*BackendSignal)(nil),      // 9: simulation.BackendSignal
	(*JobAssignment)(nil),      // 10: simulation.JobAssignment
	(*AbortSignal)(nil),        // 11: simulation.AbortSignal
}
var file_simulation_worker_proto_depIdxs = []int32{
	4,  // 0: simulation.HeartbeatResponse.recent_rewards:type_name -> simulation.RewardNotification
	7,  // 1: simulation.WorkerSignal.progress:type_name -> simulation.WorkerProgress
	8,  // 2: simulation.WorkerSignal.result:type_name -> simulation.JobResult
	0,  // 3: simulation.JobResult.error_code:type_name -> simulation.WorkerErrorCode
	10, // 4: simulation.BackendSignal.job_assignment:type_name -> simulation.JobAssignment
	11, // 5: simulation.BackendSignal.abort_signal:type_name -> simulation.AbortSignal
	3,  // 6: simulation.SimulationWorkerService.SendHeartbeat:input_type -> simulation.HeartbeatRequest
	6,  // 7: simulation.SimulationWorkerService.StreamJobChannel:input_type -> simulation.WorkerSignal
	1,  // 8: simulation.ValidatorService.ValidateJob:input_type -> simulation.ValidationRequest
	5,  // 9: simulation.SimulationWorkerService.SendHeartbeat:output_type -> simulation.HeartbeatResponse
	9,  // 10: simulation.SimulationWorkerService.StreamJobChannel:output_type -> simulation.BackendSignal
	2,  // 11: simulation.ValidatorService.ValidateJob:output_type -> simulation.ValidationResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_simulation_worker_proto_init() }
func file_simulation_worker_proto_init() {
	if File_simulation_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simulation_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewardNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulation_worker_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_simulation_worker_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*WorkerSignal_Progress)(nil),
		(*WorkerSignal_Result)(nil),
	}
	file_simulation_worker_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*BackendSignal_JobAssignment)(nil),
		(*BackendSignal_AbortSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simulation_worker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_simulation_worker_proto_goTypes,
		DependencyIndexes: file_simulation_worker_proto_depIdxs,
		EnumInfos:         file_simulation_worker_proto_enumTypes,
		MessageInfos:      file_simulation_worker_proto_msgTypes,
	}.Build()
	File_simulation_worker_proto = out.File
	file_simulation_worker_proto_rawDesc = nil
	file_simulation_worker_proto_goTypes = nil
	file_simulation_worker_proto_depIdxs = nil
}
